Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ming/Documents/TieComm/main.py", line 175, in <module>
    main(args)
  File "/Users/ming/Documents/TieComm/main.py", line 80, in main
    env = env_REGISTRY[args.env](env_config)
  File "/Users/ming/Documents/TieComm/envs/pz_wrappers.py", line 20, in __init__
    self._env = gym.make('pz-mpe-large-spread-v1', **config)
  File "/opt/anaconda3/envs/tiecomm/lib/python3.8/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/opt/anaconda3/envs/tiecomm/lib/python3.8/site-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/opt/anaconda3/envs/tiecomm/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = cls(**_kwargs)
TypeError: __init__() got an unexpected keyword argument 'env'